name    'saschajulien-mailserver'
version '0.0.4'
source 'https://github.com/saschajulien/mailserver.git'
author 'mjhas, saschajulien'
license 'Apache License 2.0'
summary ''
description 'This Module provides a mailserver with postfix as SMTP-Server and dovecot as IMAP Server with virtual configuration stored in a postgres database '
project_page 'https://github.com/saschajulien/mailserver.git'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'saschajulien-amavis', '0.0.2'
dependency 'saschajulien-clamav', '0.0.1'
dependency 'saschajulien-dovecot', '0.0.7'
dependency 'saschajulien-postfix', '0.0.6'
dependency 'puppetlabs-postgresql', '3.4.0'
